env: dev

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

envVars:
  DB_HOST: nodeapi-postgres
  DB_NAME: nodeapidb
  DB_USER: devuser
  DB_PASSWORD: devpass

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

postgres:
  image: postgres:13
  storage: 1Gi
  user: devuser
  password: devpass
  dbName: nodeapidb

quota:
  requests:
    cpu: "600m"
    memory: "768Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

limitRange:
  defaultRequest:
    cpu: "100m"
    memory: "128Mi"
  default:
    cpu: "300m"
    memory: "256Mi"

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
