apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limits
  namespace: {{ .Release.Namespace }}
spec:
  limits:
    - defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequest.cpu | quote }}
        memory: {{ .Values.limitRange.defaultRequest.memory | quote }}
      default:
        cpu: {{ .Values.limitRange.default.cpu | quote }}
        memory: {{ .Values.limitRange.default.memory | quote }}
      type: Container
