apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    requests.cpu: {{ .Values.quota.requests.cpu | quote }}
    requests.memory: {{ .Values.quota.requests.memory | quote }}
    limits.cpu: {{ .Values.quota.limits.cpu | quote }}
    limits.memory: {{ .Values.quota.limits.memory | quote }}
